# Generated by Django 3.0.3 on 2020-03-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SyntaxCheckerApp', '0002_auto_20200326_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.RemoveField(
            model_name='timeadverb',
            name='tense',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='noun',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='tense',
        ),
        migrations.DeleteModel(
            name='Noun',
        ),
        migrations.DeleteModel(
            name='Tense',
        ),
        migrations.DeleteModel(
            name='TimeAdverb',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
